### ISSUE TITLE
Warning in console re select

### ISSUE THREAD

**Issue by egli** [sbsdev/daisyproducer2#79]
The console shows a warning, apparently the selects aren't coded properly

```
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
option
select
div
div
div
cmp@http://localhost:3000/js/out/reagent/impl/component.js:517:54
div
div
section
cmp@http://localhost:3000/js/out/reagent/impl/component.js:517:54
div
cmp@http://localhost:3000/js/out/reagent/impl/component.js:517:54 react-dom.inc.js:61:32
```

**Comment by plexus** [comment]
Yes, this is a difference between React and normal HTML. It's actually a more convenient model once you are used to it. ([React docs](https://reactjs.org/docs/forms.html#the-select-tag))

In reagent that becomes something like this.

```clj
(defn my-select []
  (let [selected (reagent/atom "apples")]
    (fn []
      [:select {:value @selected :on-change #(reset! selected (.. % -target -value))}
       [:option {:value "apples"} "Apples"]
       [:option {:value "pears"} "Pears"]
       [:option {:value "oranges"} "Oranges"]])))
```

For an uncontrolled component use `:default-value` instead of `:value` ([React docs](https://reactjs.org/docs/uncontrolled-components.html)).
